Instruction:
  ADD [source, destination]

Description:
  Копирует файлы или директории из контекста сборки в образ Docker. 
  Может автоматически распаковывать файлы с расширением .tar, .tar.gz, .tar.bz2 или .tar.xz.

Features:
  - Поддерживает URL-адреса в качестве источника копирования.
  - Автоматически распаковывает архивы.

Limitations:
  - Не поддерживает копирование файлов с URL-адресов.
  - Неясно, как ADD обрабатывает метаданные файлов.

Instruction:
  COPY [source, destination]

Description:
  Копирует файлы или директории из контекста сборки в образ Docker.

Features:
  - Простой в использовании.
  - Явно копирует файлы или директории.

Limitations:
  - Не поддерживает URL-адреса в качестве источника копирования.
  - Не автоматически распаковывает архивы.


# ADD пример
FROM ubuntu
ADD https://example.com/archive.tar.gz /tmp/
RUN tar -C /usr/local -xzf /tmp/archive.tar.gz

# COPY пример
FROM ubuntu
COPY ./src /app/src
COPY ./static /app/static


Instruction:
  ENTRYPOINT ["executable", "param1", "param2"]

Description:
  Задает исполняемый файл, который должен быть запущен при запуске контейнера.

Features:
  - Задает основной исполняемый файл для контейнера.
  - Параметры командной строки могут быть указаны как аргументы к ENTRYPOINT.

Limitations:
  - Аргументы к ENTRYPOINT могут быть перезаписаны при запуске контейнера с помощью ключа командной строки --entrypoint.


Instruction:
  CMD ["executable", "param1", "param2"]
  CMD command param1 param2

Description:
  Задает команду по умолчанию, которая будет выполняться при запуске контейнера.

Features:
  - Позволяет задать команду по умолчанию, которая будет выполняться при запуске контейнера.
  - Позволяет переопределить команду по умолчанию при запуске контейнера с помощью ключа командной строки --cmd.

Limitations:
  - В Dockerfile может быть только одна инструкция CMD.
  - CMD не заменяет ENTRYPOINT, а дополняет его.

# ENTRYPOINT пример
FROM ubuntu
ENTRYPOINT ["ping", "-c", "3"]
CMD ["google.com"]

# CMD пример
FROM ubuntu
CMD ["ping", "-c", "3", "google.com"]
