# Display current rules: 
iptables -L

# Flush all rules: 
iptables -F

# Allow incoming SSH traffic: 
iptables -A INPUT -p tcp --dport 22 -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT

# Allow outgoing SSH traffic: 
iptables -A OUTPUT -p tcp --sport 22 -m conntrack --ctstate ESTABLISHED -j ACCEPT

# Block all incoming traffic: 
iptables -P INPUT DROP

# Block all outgoing traffic: 
iptables -P OUTPUT DROP

# Allow incoming traffic from specific IP address: 
iptables -A INPUT -s [IP ADDRESS] -j ACCEPT

# Allow outgoing traffic to specific IP address: 
iptables -A OUTPUT -d [IP ADDRESS] -j ACCEPT

# Block incoming traffic to specific port: 
iptables -A INPUT -p tcp --dport [PORT NUMBER] -j DROP

# Block outgoing traffic to specific port: 
iptables -A OUTPUT -p tcp --dport [PORT NUMBER] -j DROP
---


- hook: PREROUTING
  description: Processes incoming packets before the routing decision is made.
  example:
    - rule: iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
      explanation: Redirect incoming HTTP traffic (port 80) to port 8080.

- hook: INPUT
  description: Processes incoming packets destined for the local system.
  example:
    - rule: iptables -A INPUT -p tcp --dport 22 -j ACCEPT
      explanation: Allow incoming SSH traffic (port 22) to the local system.

- hook: FORWARD
  description: Processes packets that need to be forwarded to another device.
  example:
    - rule: iptables -A FORWARD -i eth0 -o eth1 -j ACCEPT
      explanation: Allow packets from interface eth0 to be forwarded to interface eth1.

- hook: OUTPUT
  description: Processes outgoing packets generated by the local system.
  example:
    - rule: iptables -A OUTPUT -p tcp --dport 80 -j DROP
      explanation: Block outgoing HTTP traffic (port 80) from the local system.

- hook: POSTROUTING
  description: Processes packets after routing decisions and just before they leave the system.
  example:
    - rule: iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      explanation: Apply Network Address Translation (NAT) to packets leaving the system through eth0.


